name: Docker Image CI

on:
    workflow_dispatch:
        inputs:
            image_purpose:
                description: 'Purpose of the image'
                required: true
                type: choice
                options:
                    - testing
                    - production
            perl_version:
                description: 'Version of Perl to build from (will always be alpine)'
                required: true
                default: '2.8.4'
            autotranslate_version:
                description: 'Version number of AutoTranslate script'
                required: true
                default: '2.2.0b'
                    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
    
        - name: Run date command
          id: date
          run: |
            buildTime=$(date +%Y-%m-%d" "%X)
            echo "BUILD_TIME=$buildTime" >> $GITHUB_OUTPUT
    
        - name: Set GH_TAG
          id: tag
          run: |
            if [ "${{ github.event.inputs.image_purpose }}" == "testing" ]; then
              buildTag=$(date +%Y-%m-%d-%H-%M)
              echo "GH_BUILD_TAG=$buildTag" >> $GITHUB_OUTPUT
              echo "GH_LATEST_TAG=testing" >> $GITHUB_OUTPUT
            elif [ "${{ github.event.inputs.image_purpose }}" == "production" ]; then
              echo "GH_BUILD_TAG=${{ github.event.inputs.autotranslate_version }}" >> $GITHUB_OUTPUT
              echo "GH_LATEST_TAG=latest" >> $GITHUB_OUTPUT
            else
              echo "Invalid purpose type specified" >&2
              exit 1
            fi
    
        - name: Login to DockerHub
          uses: docker/login-action@v3 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            platforms: linux/amd64
            # platforms: linux/amd64,linux/arm64
            # platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:${{ steps.tag.outputs.GH_BUILD_TAG }}
              ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:${{ steps.tag.outputs.GH_LATEST_TAG }}
            build-args: |
              BUILD_TIME=${{ steps.date.outputs.BUILD_TIME }}
              SCRIPT_VERSION=${{ github.event.inputs.autotranslate_version }}
              PERL_VERSION=${{ github.event.inputs.perl_version }}
